# Generated by Django 5.0.6 on 2024-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(max_length=100, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_cuenta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
