# Generated by Django 5.0.6 on 2024-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
