# Generated by Django 4.2.13 on 2024-06-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_cuenta',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
