# Generated by Django 4.2.13 on 2024-06-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_cliente_fecha_cuenta_remove_cliente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='nombre_user',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
    ]
