# Generated by Django 4.2.13 on 2024-07-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_username_cliente_nombre_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='suscripcion',
            fields=[
                ('id_suscripcion', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
    ]
