# Generated by Django 4.2.13 on 2024-07-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='subscription',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='clients.suscripcion'),
            preserve_default=False,
        ),
    ]
